main = "build"
project = "mazelock"

[[stages]]
name = "build"
description = "Build mazelock binary"
type = "premake5"
outputs = ["root://bin/mazelock"]
clean = true
clean_paths = ["root://obj"]
# config = "debug"
# strip = false

[install]
depends = ["build"]
artifacts = [
    { source = "root://bin/mazelock", dest = "mazelock" },
]

[[stages]]
name = "clean"
description = "Clean build artifacts"
type = "clean"
targets = ["build"]
